/**
 * madana-api
 * <h1>API Quickstart Guide</h1>        <p>This documentation contains a Quickstart Guide, a few <a href=\"downloads.html\">sample clients</a>  for download and information about the available  <a href=\"resources.html\">endpoints</a>  and  <a href=\"data.html\">DataTypes</a>  </p>     <p>The <a target=\"_blank\" href=\"http://madana-explorer-staging.eu-central-1.elasticbeanstalk.com/login\">  MADANA Explorer</a> can be used to verify the interactions with the API</p>           <p>Internal use only. For more information visit <a href=\"https://www.madana.io\">www.madana.io</a></p>         <br> <br>
 *
 * The version of the OpenAPI document: 0.4.12
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 4.3.0.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



#include "Json_DatasetInfo_allOf.h"

namespace com {
namespace madana {
namespace client {
namespace model {




Json_DatasetInfo_allOf::Json_DatasetInfo_allOf()
{
    m_Signature = utility::conversions::to_string_t("");
    m_SignatureIsSet = false;
    m_Size = utility::conversions::to_string_t("");
    m_SizeIsSet = false;
    m_Hash = utility::conversions::to_string_t("");
    m_HashIsSet = false;
    m_Creationdate = utility::conversions::to_string_t("");
    m_CreationdateIsSet = false;
    m_Fingerprint = utility::conversions::to_string_t("");
    m_FingerprintIsSet = false;
}

Json_DatasetInfo_allOf::~Json_DatasetInfo_allOf()
{
}

void Json_DatasetInfo_allOf::validate()
{
    // TODO: implement validation
}

web::json::value Json_DatasetInfo_allOf::toJson() const
{

    web::json::value val = web::json::value::object();
    
    if(m_SignatureIsSet)
    {
        val[utility::conversions::to_string_t("signature")] = ModelBase::toJson(m_Signature);
    }
    if(m_SizeIsSet)
    {
        val[utility::conversions::to_string_t("size")] = ModelBase::toJson(m_Size);
    }
    if(m_HashIsSet)
    {
        val[utility::conversions::to_string_t("hash")] = ModelBase::toJson(m_Hash);
    }
    if(m_CreationdateIsSet)
    {
        val[utility::conversions::to_string_t("creationdate")] = ModelBase::toJson(m_Creationdate);
    }
    if(m_FingerprintIsSet)
    {
        val[utility::conversions::to_string_t("fingerprint")] = ModelBase::toJson(m_Fingerprint);
    }

    return val;
}

bool Json_DatasetInfo_allOf::fromJson(const web::json::value& val)
{
    bool ok = true;
    
    if(val.has_field(utility::conversions::to_string_t("signature")))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t("signature"));
        if(!fieldValue.is_null())
        {
            utility::string_t refVal_signature;
            ok &= ModelBase::fromJson(fieldValue, refVal_signature);
            setSignature(refVal_signature);
        }
    }
    if(val.has_field(utility::conversions::to_string_t("size")))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t("size"));
        if(!fieldValue.is_null())
        {
            utility::string_t refVal_size;
            ok &= ModelBase::fromJson(fieldValue, refVal_size);
            setSize(refVal_size);
        }
    }
    if(val.has_field(utility::conversions::to_string_t("hash")))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t("hash"));
        if(!fieldValue.is_null())
        {
            utility::string_t refVal_hash;
            ok &= ModelBase::fromJson(fieldValue, refVal_hash);
            setHash(refVal_hash);
        }
    }
    if(val.has_field(utility::conversions::to_string_t("creationdate")))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t("creationdate"));
        if(!fieldValue.is_null())
        {
            utility::string_t refVal_creationdate;
            ok &= ModelBase::fromJson(fieldValue, refVal_creationdate);
            setCreationdate(refVal_creationdate);
        }
    }
    if(val.has_field(utility::conversions::to_string_t("fingerprint")))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t("fingerprint"));
        if(!fieldValue.is_null())
        {
            utility::string_t refVal_fingerprint;
            ok &= ModelBase::fromJson(fieldValue, refVal_fingerprint);
            setFingerprint(refVal_fingerprint);
        }
    }
    return ok;
}

void Json_DatasetInfo_allOf::toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& prefix) const
{
    utility::string_t namePrefix = prefix;
    if(namePrefix.size() > 0 && namePrefix.substr(namePrefix.size() - 1) != utility::conversions::to_string_t("."))
    {
        namePrefix += utility::conversions::to_string_t(".");
    }
    if(m_SignatureIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t("signature"), m_Signature));
    }
    if(m_SizeIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t("size"), m_Size));
    }
    if(m_HashIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t("hash"), m_Hash));
    }
    if(m_CreationdateIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t("creationdate"), m_Creationdate));
    }
    if(m_FingerprintIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t("fingerprint"), m_Fingerprint));
    }
}

bool Json_DatasetInfo_allOf::fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& prefix)
{
    bool ok = true;
    utility::string_t namePrefix = prefix;
    if(namePrefix.size() > 0 && namePrefix.substr(namePrefix.size() - 1) != utility::conversions::to_string_t("."))
    {
        namePrefix += utility::conversions::to_string_t(".");
    }

    if(multipart->hasContent(utility::conversions::to_string_t("signature")))
    {
        utility::string_t refVal_signature;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t("signature")), refVal_signature );
        setSignature(refVal_signature);
    }
    if(multipart->hasContent(utility::conversions::to_string_t("size")))
    {
        utility::string_t refVal_size;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t("size")), refVal_size );
        setSize(refVal_size);
    }
    if(multipart->hasContent(utility::conversions::to_string_t("hash")))
    {
        utility::string_t refVal_hash;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t("hash")), refVal_hash );
        setHash(refVal_hash);
    }
    if(multipart->hasContent(utility::conversions::to_string_t("creationdate")))
    {
        utility::string_t refVal_creationdate;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t("creationdate")), refVal_creationdate );
        setCreationdate(refVal_creationdate);
    }
    if(multipart->hasContent(utility::conversions::to_string_t("fingerprint")))
    {
        utility::string_t refVal_fingerprint;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t("fingerprint")), refVal_fingerprint );
        setFingerprint(refVal_fingerprint);
    }
    return ok;
}

utility::string_t Json_DatasetInfo_allOf::getSignature() const
{
    return m_Signature;
}

void Json_DatasetInfo_allOf::setSignature(const utility::string_t& value)
{
    m_Signature = value;
    m_SignatureIsSet = true;
}

bool Json_DatasetInfo_allOf::signatureIsSet() const
{
    return m_SignatureIsSet;
}

void Json_DatasetInfo_allOf::unsetSignature()
{
    m_SignatureIsSet = false;
}
utility::string_t Json_DatasetInfo_allOf::getSize() const
{
    return m_Size;
}

void Json_DatasetInfo_allOf::setSize(const utility::string_t& value)
{
    m_Size = value;
    m_SizeIsSet = true;
}

bool Json_DatasetInfo_allOf::sizeIsSet() const
{
    return m_SizeIsSet;
}

void Json_DatasetInfo_allOf::unsetSize()
{
    m_SizeIsSet = false;
}
utility::string_t Json_DatasetInfo_allOf::getHash() const
{
    return m_Hash;
}

void Json_DatasetInfo_allOf::setHash(const utility::string_t& value)
{
    m_Hash = value;
    m_HashIsSet = true;
}

bool Json_DatasetInfo_allOf::hashIsSet() const
{
    return m_HashIsSet;
}

void Json_DatasetInfo_allOf::unsetHash()
{
    m_HashIsSet = false;
}
utility::string_t Json_DatasetInfo_allOf::getCreationdate() const
{
    return m_Creationdate;
}

void Json_DatasetInfo_allOf::setCreationdate(const utility::string_t& value)
{
    m_Creationdate = value;
    m_CreationdateIsSet = true;
}

bool Json_DatasetInfo_allOf::creationdateIsSet() const
{
    return m_CreationdateIsSet;
}

void Json_DatasetInfo_allOf::unsetCreationdate()
{
    m_CreationdateIsSet = false;
}
utility::string_t Json_DatasetInfo_allOf::getFingerprint() const
{
    return m_Fingerprint;
}

void Json_DatasetInfo_allOf::setFingerprint(const utility::string_t& value)
{
    m_Fingerprint = value;
    m_FingerprintIsSet = true;
}

bool Json_DatasetInfo_allOf::fingerprintIsSet() const
{
    return m_FingerprintIsSet;
}

void Json_DatasetInfo_allOf::unsetFingerprint()
{
    m_FingerprintIsSet = false;
}
}
}
}
}


