/**
 * madana-api
 * <h1>Using the madana-api</h1>        <p>This documentation contains a Quickstart Guide, relating client functionality and information about the available         endpoints and used datamodels.   </p>       <p> The madana-api and its implementations are still in heavy development. This means that there may be problems in our protocols, or there may be mistakes in our implementations. We take security vulnerabilities very seriously. If you discover a security issue, please bring it to our attention right away! If you find a vulnerability that may affect live deployments -- for example, by exposing a remote execution exploit -- please send your report privately to info@madana.io. Please DO NOT file a public issue. If the issue is a protocol weakness that cannot be immediately exploited or something not yet deployed, just discuss it openly   </p>   <br>   <p> Note: Not all functionality might be acessible without having accquired and api-license token. For more information visit <a href=\"https://www.madana.io\">www.madana.io</a> </p>       <br>
 *
 * The version of the OpenAPI document: 0.4.15-master.11
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 5.0.0-beta2.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/*
 * Json_EnvironmentPublishingRequest.h
 *
 * 
 */

#ifndef COM_MADANA_APICLIENT_MODEL_Json_EnvironmentPublishingRequest_H_
#define COM_MADANA_APICLIENT_MODEL_Json_EnvironmentPublishingRequest_H_


#include "../ModelBase.h"

#include <cpprest/details/basic_types.h>

namespace com {
namespace madana {
namespace apiclient {
namespace model {


/// <summary>
/// 
/// </summary>
class  Json_EnvironmentPublishingRequest
    : public ModelBase
{
public:
    Json_EnvironmentPublishingRequest();
    virtual ~Json_EnvironmentPublishingRequest();

    /////////////////////////////////////////////
    /// ModelBase overrides

    void validate() override;

    web::json::value toJson() const override;
    bool fromJson(const web::json::value& json) override;

    void toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) const override;
    bool fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) override;

    /////////////////////////////////////////////
    /// Json_EnvironmentPublishingRequest members

    /// <summary>
    /// 
    /// </summary>
    utility::string_t getIpfsHash() const;
    bool ipfsHashIsSet() const;
    void unsetIpfsHash();

    void setIpfsHash(const utility::string_t& value);

    /// <summary>
    /// 
    /// </summary>
    utility::string_t getIpfsPrimaryPeer() const;
    bool ipfsPrimaryPeerIsSet() const;
    void unsetIpfsPrimaryPeer();

    void setIpfsPrimaryPeer(const utility::string_t& value);

    /// <summary>
    /// 
    /// </summary>
    utility::string_t getDescription() const;
    bool descriptionIsSet() const;
    void unsetDescription();

    void setDescription(const utility::string_t& value);

    /// <summary>
    /// 
    /// </summary>
    utility::string_t getUuid() const;
    bool uuidIsSet() const;
    void unsetUuid();

    void setUuid(const utility::string_t& value);

    /// <summary>
    /// 
    /// </summary>
    utility::string_t getContent() const;
    bool contentIsSet() const;
    void unsetContent();

    void setContent(const utility::string_t& value);

    /// <summary>
    /// 
    /// </summary>
    utility::string_t getPackages() const;
    bool packagesIsSet() const;
    void unsetPackages();

    void setPackages(const utility::string_t& value);

    /// <summary>
    /// 
    /// </summary>
    utility::string_t getIsPublic() const;
    bool isPublicIsSet() const;
    void unsetIsPublic();

    void setIsPublic(const utility::string_t& value);

    /// <summary>
    /// 
    /// </summary>
    utility::string_t getName() const;
    bool nameIsSet() const;
    void unsetName();

    void setName(const utility::string_t& value);

    /// <summary>
    /// 
    /// </summary>
    utility::string_t getSize() const;
    bool sizeIsSet() const;
    void unsetSize();

    void setSize(const utility::string_t& value);


protected:
    utility::string_t m_IpfsHash;
    bool m_IpfsHashIsSet;
    utility::string_t m_IpfsPrimaryPeer;
    bool m_IpfsPrimaryPeerIsSet;
    utility::string_t m_Description;
    bool m_DescriptionIsSet;
    utility::string_t m_Uuid;
    bool m_UuidIsSet;
    utility::string_t m_Content;
    bool m_ContentIsSet;
    utility::string_t m_Packages;
    bool m_PackagesIsSet;
    utility::string_t m_IsPublic;
    bool m_IsPublicIsSet;
    utility::string_t m_Name;
    bool m_NameIsSet;
    utility::string_t m_Size;
    bool m_SizeIsSet;
};


}
}
}
}

#endif /* COM_MADANA_APICLIENT_MODEL_Json_EnvironmentPublishingRequest_H_ */
