/**
 * madana-api
 * <h1>API Quickstart Guide</h1>        <p>This documentation contains a Quickstart Guide, a few <a href=\"downloads.html\">sample clients</a>  for download and information about the available  <a href=\"resources.html\">endpoints</a>  and  <a href=\"data.html\">DataTypes</a>  </p>     <p>The <a target=\"_blank\" href=\"http://madana-explorer-staging.eu-central-1.elasticbeanstalk.com/login\">  MADANA Explorer</a> can be used to verify the interactions with the API</p>           <p>Internal use only. For more information visit <a href=\"https://www.madana.io\">www.madana.io</a></p>         <br> <br>
 *
 * The version of the OpenAPI document: 0.4.12
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 4.3.0.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/*
 * SocialServiceApi.h
 *
 * 
 */

#ifndef   COM_MADANA_CLIENT_API_SocialServiceApi_H_
#define   COM_MADANA_CLIENT_API_SocialServiceApi_H_


#include "../ApiClient.h"

#include "HttpContent.h"
#include <cpprest/details/basic_types.h>
#include "../ModelBase.h"

#include <boost/optional.hpp>

namespace   com {
namespace madana {
namespace client {
namespace api {

using namespace com::madana::client::model;



class  SocialServiceApi 
{
public:

    explicit SocialServiceApi( std::shared_ptr<const ApiClient> apiClient );

    virtual ~SocialServiceApi();

    /// <summary>
    /// 
    /// </summary>
    /// <remarks>
    /// 
    /// </remarks>
    pplx::task<std::shared_ptr<HttpContent>> getMyProfile(
    ) const;
    /// <summary>
    /// Returns all Platforms / Systems that can be Connected to the MADANA Service.
    /// </summary>
    /// <remarks>
    /// Returns all Platforms / Systems that can be Connected to the MADANA Service
    /// </remarks>
    pplx::task<std::shared_ptr<HttpContent>> getPlatforms2(
    ) const;
    /// <summary>
    /// Returns the Ranking by PTS within the System.
    /// </summary>
    /// <remarks>
    /// Returns the Ranking by PTS within the System
    /// </remarks>
    pplx::task<std::shared_ptr<HttpContent>> getRanking(
    ) const;
    /// <summary>
    /// 
    /// </summary>
    /// <remarks>
    /// 
    /// </remarks>
    /// <param name="platform"></param>
    pplx::task<std::shared_ptr<HttpContent>> getSocialPlatformFeed(
        utility::string_t platform
    ) const;
    /// <summary>
    /// 
    /// </summary>
    /// <remarks>
    /// 
    /// </remarks>
    /// <param name="username"></param>
    /// <param name="simple"> (optional, default to utility::conversions::to_string_t(&quot;&quot;))</param>
    pplx::task<std::shared_ptr<HttpContent>> getUserProfile(
        utility::string_t username,
        boost::optional<utility::string_t> simple
    ) const;
    /// <summary>
    /// 
    /// </summary>
    /// <remarks>
    /// 
    /// </remarks>
    /// <param name="username"></param>
    pplx::task<std::shared_ptr<HttpContent>> getUserProfile_0(
        utility::string_t username
    ) const;

protected:
    std::shared_ptr<const ApiClient> m_ApiClient;
};

}
}
}
}

#endif /*   COM_MADANA_CLIENT_API_SocialServiceApi_H_ */

